### ISSUE TITLE
Day01. 当老司机学会了贪心算法

### ISSUE THREAD

**Issue by labuladong** [labuladong/practice-challenge#79]
今日学习文章：[当老司机学会了贪心算法](https://labuladong.github.io/article/fname.html?fname=老司机)

请于两天内在本 issue 下评论完成打卡，学习过程中如果遇到无法解决的问题可以在群里交流。

**Comment by fateYoung** [comment]
https://leetcode.com/problems/gas-station/discuss/2726814/gas-station

**Comment by austinxyz** [comment]
https://leetcode.com/problems/gas-station/discuss/2416244/Java-or-gredy

**Comment by Lillyzhou** [comment]
https://leetcode.com/problems/gas-station/solutions/2815216/greedy/

**Comment by jcao15** [comment]
https://leetcode.com/problems/gas-station/solutions/2728344/greedy-in-java/

**Comment by double-alt** [comment]
https://leetcode.cn/problems/gas-station/solution/by-xiao-di-ix-j5pe/

**Comment by woshierha** [comment]
https://leetcode.cn/problems/gas-station/solution/tan-xin-by-dao-ge-2r-nq1a/

**Comment by Khannoob** [comment]
https://leetcode.cn/problems/gas-station/solution/greedy-by-khannoob-y6rf/

**Comment by elekyx** [comment]
https://leetcode.cn/problems/gas-station/solutions/1971502/by-elecseaky-hmsd/

**Comment by BaoxinS** [comment]
134: https://leetcode.com/problems/gas-station/discuss/2816087/Java-Gas-Station

**Comment by jtsd2008lm** [comment]
https://leetcode.cn/problems/gas-station/solutions/1910558/jia-you-zhan-by-limeng62373791-vlf4/

**Comment by pia7a** [comment]
https://leetcode.cn/problems/gas-station/solutions/1972509/jia-you-zhan-by-pia7a-k-isag/

**Comment by jackgo73** [comment]
https://leetcode.cn/problems/gas-station/solutions/1972737/tu-fang-fa-zui-jian-dan-jie-fa-by-jackgo-we3d/

**Comment by wikyyuen** [comment]
https://leetcode.com/problems/gas-station/discuss/2817368/134.-Gas-Station

**Comment by maccoli** [comment]
https://leetcode.cn/problems/gas-station/post-solution/?submissionId=382311266

**Comment by Keying96** [comment]
https://leetcode.com/problems/gas-station/discuss/2817594/Java-or-Brute-force-solution-and-O(n)-running-time-O(1)-space-solution

**Comment by RuiLiu0129** [comment]
https://leetcode.com/problems/gas-station/solutions/2817732/easy-python-solution/

**Comment by zx0316** [comment]
https://leetcode.cn/problems/gas-station/solution/by-leematrix-olva/

**Comment by yangzho12138** [comment]
https://leetcode.cn/problems/gas-station/solution/by-bu-xiang-xie-dai-ma-de-qhei/

**Comment by whitekeepwork** [comment]
https://leetcode.com/problems/gas-station/discuss/2727759/java-greedy-solution

**Comment by lucy-xfl** [comment]
https://leetcode.com/problems/gas-station/solutions/2820025/python-greedy/

**Comment by tarian1995** [comment]
https://leetcode.cn/problems/gas-station/solutions/1974961/tan-xin-suan-fa-by-tab-o-s1dj/

**Comment by iry799** [comment]
https://github.com/labuladong/practice-challenge/issues

**Comment by goldenlimit** [comment]
Python3:
134. Gas Station https://leetcode.cn/problems/gas-station/description/
https://leetcode.cn/problems/gas-station/solutions/1692824/goldenlimit-by-goldenlimit-v7xm/

**Comment by zag13** [comment]
https://leetcode.cn/problems/gas-station/solutions/1985238/day01-dang-lao-si-ji-xue-hui-liao-tan-xi-27al/

**Comment by wodxumingxu** [comment]
https://leetcode.com/problems/gas-station/discussion/comments/1694915

**Comment by Ying97** [comment]
https://leetcode.cn/problems/gas-station/solutions/1997132/2shua-zhe-ge-ti-by-amazing-vaughan-dqsi/

**Comment by iry799** [comment]
https://leetcode.cn/problems/gas-station/solutions/1975180/tan-xin-by-u95u8p3mfg-ceu0/

**Comment by MzxlM** [comment]
https://leetcode.com/problems/gas-station/solutions/2837237/java-soltuion/

**Comment by maccoli** [comment]
https://leetcode.cn/problems/gas-station/solutions/1972787/tan-xin-qiu-jie-jia-you-zhan-by-macco-3jfd/
