### ISSUE TITLE
Day04. 括号系列问题集合

### ISSUE THREAD

**Issue by labuladong** [labuladong/practice-challenge#82]
今日学习文章：[括号系列问题集合](https://labuladong.github.io/article/fname.html?fname=括号插入)

请于两天内在本 issue 下评论完成打卡，学习过程中如果遇到无法解决的问题可以在群里交流。

**Comment by fateYoung** [comment]
https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/discuss/2825201/Minimum-Add-to-Make-Parentheses-Valid

**Comment by wikyyuen** [comment]
https://leetcode.com/problems/valid-parentheses/discuss/2825665/20.-Valid-Parentheses

**Comment by elekyx** [comment]
https://leetcode.cn/problems/minimum-add-to-make-parentheses-valid/solutions/1977852/by-elecseaky-hc88/

**Comment by woshierha** [comment]
921 https://leetcode.cn/problems/minimum-add-to-make-parentheses-valid/solution/zeng-jia-de-gua-hao-shu-liang-by-dao-ge-x4nkm/
1541 https://leetcode.cn/problems/minimum-insertions-to-balance-a-parentheses-string/solution/gua-hao-shu-liang-by-dao-ge-2r-ch4m/

**Comment by double-alt** [comment]
https://leetcode.cn/problems/minimum-insertions-to-balance-a-parentheses-string/solution/by-xiao-di-ix-5t90/

**Comment by Lillyzhou** [comment]
https://leetcode.com/problems/minimum-insertions-to-balance-a-parentheses-string/solutions/2825876/python/

**Comment by jtsd2008lm** [comment]
https://leetcode.cn/problems/valid-parentheses/solution/you-xiao-de-gua-hao-by-limeng62373791-8yit/

**Comment by jtsd2008lm** [comment]
https://leetcode.cn/problems/minimum-insertions-to-balance-a-parentheses-string/solutions/1978411/ping-heng-gua-hao-zi-fu-chuan-de-zui-sha-7ewy/

**Comment by Keying96** [comment]
https://leetcode.com/problems/valid-parentheses/discuss/2826664/Java-or-Stack-based-solution

**Comment by tarian1995** [comment]
https://leetcode.cn/problems/minimum-insertions-to-balance-a-parentheses-string/solutions/1978875/by-tab-o-589d/

**Comment by Khannoob** [comment]
https://leetcode.cn/problems/valid-parentheses/solution/stack-by-khannoob-o6x3/

**Comment by jackgo73** [comment]
https://leetcode.cn/problems/minimum-add-to-make-parentheses-valid/solution/by-jackgo-tsaj/

**Comment by maccoli** [comment]
https://leetcode.cn/problems/minimum-insertions-to-balance-a-parentheses-string/solutions/1979168/ping-heng-gua-hao-by-macco-y4ok/

**Comment by pia7a** [comment]
https://leetcode.cn/problems/minimum-insertions-to-balance-a-parentheses-string/solutions/1979186/ping-heng-gua-hao-zi-fu-chuan-de-zui-xia-xm68/

**Comment by austinxyz** [comment]
https://leetcode.com/problems/minimum-insertions-to-balance-a-parentheses-string/discuss/2413216/Java-simple-solution

**Comment by yangzho12138** [comment]
https://leetcode.cn/problems/minimum-insertions-to-balance-a-parentheses-string/solution/by-bu-xiang-xie-dai-ma-de-6y20/

**Comment by BaoxinS** [comment]
1541: https://leetcode.com/problems/minimum-insertions-to-balance-a-parentheses-string/discuss/2738135/Java-Minimum-Insertions-to-Balance-a-Parentheses-String

**Comment by zx0316** [comment]
https://leetcode.cn/problems/valid-parentheses/solution/-by-leematrix-f0jr/

**Comment by whitekeepwork** [comment]
https://leetcode.com/problems/minimum-insertions-to-balance-a-parentheses-string/discuss/2737619/java-balancer-count-solution

**Comment by goldenlimit** [comment]
Python3:
[921. Minimum Add to Make Parentheses Valid](https://leetcode.cn/problems/minimum-add-to-make-parentheses-valid/description/)
https://leetcode.cn/problems/minimum-add-to-make-parentheses-valid/solutions/1980864/goldenlimitjie-ti-bi-ji-zui-shao-tian-ji-g97e/

**Comment by zag13** [comment]
https://leetcode.cn/problems/valid-parentheses/solutions/1996526/by-xiao-niu-zi-dgpx/

**Comment by wodxumingxu** [comment]
https://leetcode.com/problems/valid-parentheses/discussion/comments/1699460

**Comment by Ying97** [comment]
https://leetcode.cn/problems/minimum-add-to-make-parentheses-valid/solutions/1997946/gua-hao-by-amazing-vaughan-b95w/

**Comment by iry799** [comment]
https://leetcode.cn/problems/minimum-insertions-to-balance-a-parentheses-string/solutions/1998064/zui-shao-cha-ru-ci-shu-by-u95u8p3mfg-2e35/

**Comment by jcao15** [comment]
https://leetcode.com/problems/minimum-insertions-to-balance-a-parentheses-string/solutions/2737380/java-simple-solution/

**Comment by MzxlM** [comment]
https://leetcode.com/problems/valid-parentheses/solutions/2837272/java-easy-solution/

**Comment by RuiLiu0129** [comment]
https://leetcode.com/problems/minimum-insertions-to-balance-a-parentheses-string/solutions/2863467/python-simple-solution/

**Comment by lucy-xfl** [comment]
https://leetcode.com/problems/valid-parentheses/solutions/2864021/python-match/
