### ISSUE TITLE
Day05. 毕业旅行省钱算法

### ISSUE THREAD

**Issue by labuladong** [labuladong/practice-challenge#83]
今日学习文章：[毕业旅行省钱算法](https://labuladong.github.io/article/fname.html?fname=旅行最短路径)

请于两天内在本 issue 下评论完成打卡，学习过程中如果遇到无法解决的问题可以在群里交流。

**Comment by fateYoung** [comment]
https://leetcode.com/problems/cheapest-flights-within-k-stops/discuss/2739760/cheapest-flights-within-k-stops

**Comment by austinxyz** [comment]
https://leetcode.com/problems/cheapest-flights-within-k-stops/discuss/2744177/Java-or-dijkstra

**Comment by Khannoob** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solution/dp-by-khannoob-jz8h/

**Comment by double-alt** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solution/787-k-zhan-zhong-zhuan-nei-zui-bian-yi-d-dtn9/

**Comment by maccoli** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solutions/1980734/by-macco-tola/

**Comment by Keying96** [comment]
https://leetcode.com/problems/cheapest-flights-within-k-stops/discuss/2830406/Java-or-3-solutions

**Comment by wikyyuen** [comment]
https://leetcode.com/problems/cheapest-flights-within-k-stops/discuss/2830572/787.-Cheapest-Flights-Within-K-Stops

**Comment by yangzho12138** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solution/by-bu-xiang-xie-dai-ma-de-t48c/

**Comment by Lillyzhou** [comment]
https://leetcode.com/problems/cheapest-flights-within-k-stops/solutions/2831030/bfs/

**Comment by woshierha** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solution/zui-bian-yi-by-dao-ge-2r-9qr5/

**Comment by pia7a** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solutions/1981159/kzhan-zhong-zhuan-nei-zui-bian-yi-de-han-7icd/

**Comment by lucy-xfl** [comment]
https://leetcode.com/problems/cheapest-flights-within-k-stops/solutions/2831572/python-dp-bfs/

**Comment by jackgo73** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solution/by-jackgo-9qk9/

**Comment by BaoxinS** [comment]
787: https://leetcode.com/problems/cheapest-flights-within-k-stops/discuss/2740930/Java-Cheapest-Flights-Within-K-Stops

**Comment by iry799** [comment]
https://github.com/labuladong/practice-challenge/issues

**Comment by iry799** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solutions/1981606/dijkstra-by-u95u8p3mfg-ycwt/

**Comment by jtsd2008lm** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solution/k-zhan-zhong-zhuan-nei-zui-bian-yi-de-ha-npva/

**Comment by zx0316** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solution/by-leematrix-dcsj/

**Comment by whitekeepwork** [comment]
https://leetcode.com/problems/cheapest-flights-within-k-stops/discuss/2745093/java-backtracking-memo

**Comment by zag13** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solutions/1996551/by-xiao-niu-zi-2dw3/

**Comment by wodxumingxu** [comment]
https://leetcode.com/problems/cheapest-flights-within-k-stops/discussion/comments/1699461

**Comment by Ying97** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solutions/1997957/dp-nk2-by-amazing-vaughan-7r3o/

**Comment by elekyx** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solutions/1998279/c-dong-tai-gui-hua-jian-dan-yi-dong-by-e-fgcm/

**Comment by jcao15** [comment]
https://leetcode.com/problems/cheapest-flights-within-k-stops/solutions/2740373/dp-solution-in-java/

**Comment by MzxlM** [comment]
https://leetcode.com/problems/cheapest-flights-within-k-stops/solutions/2837273/java-easy-understanding/

**Comment by tarian1995** [comment]
https://leetcode.cn/problems/cheapest-flights-within-k-stops/solutions/1999370/dis-by-tab-o-552k/

**Comment by RuiLiu0129** [comment]
https://leetcode.com/problems/cheapest-flights-within-k-stops/solutions/2863476/java-simple-solution/
