### ISSUE TITLE
Day06. 常用的位运算技巧

### ISSUE THREAD

**Issue by labuladong** [labuladong/practice-challenge#84]
今日学习文章：[常用的位运算技巧](https://labuladong.github.io/article/fname.html?fname=常用的位操作)

请于两天内在本 issue 下评论完成打卡，学习过程中如果遇到无法解决的问题可以在群里交流。

**Comment by fateYoung** [comment]
https://leetcode.com/problems/power-of-two/discuss/2830882/Power-of-Two

**Comment by wikyyuen** [comment]
https://leetcode.com/problems/single-number/discuss/2831137/136.-Single-Number

**Comment by austinxyz** [comment]
https://leetcode.com/problems/number-of-1-bits/discuss/2744183/Java-or-bit-manipulation

**Comment by yangzho12138** [comment]
https://leetcode.cn/problems/missing-number/solution/yi-huo-he-qiu-jie-by-bu-xiang-xie-dai-ma-egmu/

**Comment by woshierha** [comment]
https://leetcode.cn/problems/missing-number/solution/he-by-dao-ge-2r-b1dn/
https://leetcode.cn/problems/single-number/solution/yi-huo-by-dao-ge-2r-529h/

**Comment by jackgo73** [comment]
https://leetcode.cn/problems/single-number/solution/by-jackgo-3wqs/

**Comment by jackgo73** [comment]
https://leetcode.cn/problems/number-of-1-bits/solution/by-jackgo-mlkb/

**Comment by BaoxinS** [comment]
231: https://leetcode.com/problems/power-of-two/discuss/2747833/Java-Power-of-Tow

**Comment by iry799** [comment]
https://leetcode.cn/problems/single-number/solutions/1981611/ji-qiao-by-u95u8p3mfg-diyn/

**Comment by Ying97** [comment]
https://leetcode.cn/problems/power-of-two/solutions/1982051/n-n-1-by-amazing-vaughan-f86q/

**Comment by jtsd2008lm** [comment]
https://leetcode.cn/problems/missing-number/solutions/1926014/diu-shi-de-shu-zi-by-limeng62373791-dyay/

**Comment by Keying96** [comment]
https://leetcode.com/problems/number-of-1-bits/discuss/2833357/Java-or-n-and-(n-1)

**Comment by maccoli** [comment]
https://leetcode.cn/problems/single-number/solutions/1982569/yi-huo-yun-suan-fu-by-macco-6c1w/

**Comment by Lillyzhou** [comment]
https://leetcode.com/problems/number-of-1-bits/solutions/2834323/bit-calculation/

**Comment by double-alt** [comment]
https://leetcode.cn/problems/power-of-two/solution/by-xiao-di-ix-hwv2/

**Comment by pia7a** [comment]
https://leetcode.cn/problems/missing-number/solutions/1983123/diu-shi-de-shu-zi-by-pia7a-k-z6gy/

**Comment by tarian1995** [comment]
https://leetcode.cn/problems/er-jin-zhi-zhong-1de-ge-shu-lcof/submissions/383833114/

**Comment by tarian1995** [comment]
https://leetcode.cn/problems/er-jin-zhi-zhong-1de-ge-shu-lcof/solutions/1984097/by-tab-o-ldbx/

**Comment by Khannoob** [comment]
https://leetcode.cn/problems/number-of-1-bits/solution/hamming-by-khannoob-0c26/

**Comment by zx0316** [comment]
https://leetcode.cn/problems/number-of-1-bits/solution/by-leematrix-6ya1/
https://leetcode.cn/problems/power-of-two/solution/by-leematrix-rwzj/

**Comment by leematrix** [comment]
https://leetcode.cn/problems/power-of-two/solution/by-leematrix-rwzj/

**Comment by lucy-xfl** [comment]
https://leetcode.com/problems/number-of-1-bits/solutions/2836497/python-by-operators/

**Comment by zag13** [comment]
https://leetcode.cn/problems/single-number/solutions/1996569/by-xiao-niu-zi-xw2i/

**Comment by wodxumingxu** [comment]
https://leetcode.com/problems/number-of-1-bits/discussion/comments/1699462

**Comment by elekyx** [comment]
https://leetcode.cn/problems/single-number/solutions/1998287/by-elecseaky-mslg/

**Comment by jcao15** [comment]
https://leetcode.com/problems/missing-number/solutions/2754069/use-xor-bit-manipulation-in-java/

**Comment by MzxlM** [comment]
https://leetcode.com/problems/missing-number/solutions/2837278/java-easy-solution/

**Comment by whitekeepwork** [comment]
https://leetcode.com/problems/single-number/discuss/2745155/bitwise-one-pass-java-solution

**Comment by RuiLiu0129** [comment]
https://leetcode.com/problems/single-number/solutions/2863482/java-solution/
